# Generated by Django 4.2.4 on 2023-08-27 12:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_userfollowdata_posts_userfollowdata_unique_followers'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLikes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_users', to='network.posts')),
                ('like_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_posts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='userlikes',
            constraint=models.UniqueConstraint(fields=('like_user', 'like_post'), name='unique_likes'),
        ),
    ]
