# Generated by Django 4.2.4 on 2023-08-28 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='comment_likes',
            field=models.IntegerField(default=0),
        ),
    ]
