# Generated by Django 4.2.4 on 2023-08-28 12:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_comments_comment_likes'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentLikes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_like_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_like_user', to=settings.AUTH_USER_MODEL)),
                ('comment_liked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_liked', to='network.comments')),
            ],
        ),
        migrations.AddConstraint(
            model_name='commentlikes',
            constraint=models.UniqueConstraint(fields=('comment_like_user', 'comment_liked'), name='unique_comment_likes'),
        ),
    ]
